
server:
  port: 8030

spring:
  profiles: dev
  application:
    name: dev-config-client
       
---

server:
  port: 8031

spring:
  profiles: test
  application:
    name: test-config-client

---

server:
  port: 8032

spring:
  profiles: pro
  application:
    name: pro-config-client