spring:
  profiles: dev
  application:
    name: dev-config-client


  profiles: test
  application:
    name: test-config-client
    
    
  profiles: pro
  application:
    name: pro-config-client
    
    
